package app.snippets;

public enum SnippetsKey {
	IF, FOR, WHILE, MAIN, SYSOUT, CLASS, INTERFACE, ENUM, TRY_CATCH, 
	SWITCH, CASE, METHOD, CONSTRUCTOR, IMPORT, PACKAGE, STATIC_BLOCK, LAMBDA_EXPRESSION,
	ANNOTATION, ASSERTION, SYNCHRONIZED_BLOCK, 
	FINAL_VARIABLE, VAR_DECLARATION, INSTANCEOF_CHECK,
	THROW_EXCEPTION, THROWS_DECLARATION;
	
}
